language: python
python:
- '2.7'

install:
    - pip install coveralls
    - 'if [ ${TRAVIS_BRANCH} \!= "master" ] && [ -f dev_requirements.txt ]; then
    	    python setup.py install;
        else
            pip install -r dev_requirements.txt;
    	    python setup.py develop --no-deps;
        fi'
    - pip install -r SDN-ODL-Lithium_Shell_Package/Resource\ Drivers\ -\ Python/Generic\ SDN\ ODL\ Helium\ Controller/requirements.txt
    - pip install -r test_requirements.txt

script:
    - nosetests --with-coverage --cover-package=src,cloudshell.networking.odl tests

after_success:
    - coveralls